apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-example
  labels:
    app: multi-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-example
  template:
    metadata:
      labels:
        app: multi-example
    spec:
      containers:
      - name: app-container
        image: nginx:latest  # Main application container
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /  # Health check endpoint
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
      - name: logging-container
        image: busybox  # Simple logging sidecar
        command: ["sh", "-c", "tail -f /var/log/app.log"]
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: log-volume
        emptyDir: {}
