apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-job
spec:
  schedule: "*/7 * * * *"  # Runs every 7 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clean
            image: gcr.io/k8s-k3s/demo:v1.0.0  # Change to your image if needed
            command: ["/bin/sh", "-c", "/path/to/clean.sh"]  # Adjust the path to clean.sh
          restartPolicy: Never
