apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gcr.io/k8s-k3s/demo:v1.0.0
        command: ["your-command", "arg1", "arg2"]  # Replace with your actual command and arguments
      restartPolicy: Never
  backoffLimit: 4
